// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_highscores = "CggIur-G3kwQAhAA"; // <GPGSID>
        public const string achievement_lose_century = "CggIur-G3kwQAhAK"; // <GPGSID>
        public const string achievement_score_50 = "CggIur-G3kwQAhAG"; // <GPGSID>
        public const string achievement_noob = "CggIur-G3kwQAhAC"; // <GPGSID>
        public const string achievement_hard_30 = "CggIur-G3kwQAhAI"; // <GPGSID>
        public const string achievement_score_30 = "CggIur-G3kwQAhAF"; // <GPGSID>
        public const string achievement_score_15 = "CggIur-G3kwQAhAE"; // <GPGSID>
        public const string achievement_score_5 = "CggIur-G3kwQAhAD"; // <GPGSID>
        public const string achievement_hard_15 = "CggIur-G3kwQAhAH"; // <GPGSID>
        public const string achievement_tough_easy_5 = "CggIur-G3kwQAhAJ"; // <GPGSID>

}

